# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e474738f79b71305a815559751b9e45489c0b0a0340dae0187979da4fc139bc7faaea959d65f1cc3e1379f4982f272342c1ae18f9173cadaa41e216b1e7d4a0a

test:
  secret_key_base: 02c80c517888ceaf6ca4e13287f760e5ff7fed90a93bcb73d0ee3c9398bb75916cc7bcc66dc1069b7792de20dc7c6396a87ecd760c2bb13af3b96ba732896211

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
